language: java

branches:
  only:
    - master
before_install:
  - chmod +x gradlew

# Travis CI Server Home
cache:
  directories:
    - '$HOME/ .m2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r study *
  - mkdir -p deploy
  - mv study.zip deploy/study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sjkim-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sjkim-springboot-build
    key: study.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람 220607
notifications:
  email:
    recipients:
      - 94kimseongjun@gmail.com